### ISSUE TITLE
Move 'use v6' statement to be compatible with upcoming 6.d release

### ISSUE THREAD

**Issue by SqrtNegInf** [zostay/perl6-ArrayHash#10]
To be compatible with the upcoming 6.d release, move the 'use v6' statement to be the very first line of ArrayHash.pm6, otherwise users of your module will bump into the error:

`Too late to switch language version. Must be used as the very first statement.`

BTW: I'm using ArrayHash to facilitate my smoke-testing of the Rosetta-code Perl 6 tasks. There are several cases where I really couldn't manage without it, so ++ for writing this module.

**Comment by SqrtNegInf** [comment]
That would seem to do the trick.  I haven't seen this change show up at modules.perl6.org, maybe that's a separate step you need to take?

**Comment by zostay** [comment]
I have it ready to release, I just hadn't yet because tests are still failing. I was hoping to get that done, but haven't made time yet. I'll go ahead with it because a module with 1 problem instead of to is still an improvement.
