### ISSUE TITLE
Tests are failing on 2018.06

### ISSUE THREAD

**Issue by zostay** [zostay/perl6-ArrayHash#8]
These failures are non-deterministic even though I am working to guarantee the test run order. Failures are pretty frequent, happening about every other test run.

**Comment by zostay** [comment]
The `t/array-hash.t` test was failing due to an incorrect assumption when creating the test iterator with `make-iter()` in the test. It assumed that .values would always match up with key order. This assumption is true 4 cases of 6:

```
a => 1, b => 2, c => 3 -- 1, 2, 3 -- GOOD
a => 1, c => 3, b => 2 -- 1, 3, 2 -- GOOD
b => 2, a => 1, c => 3 -- 2, 1, 3 -- GOOD
c => 3, b => 2, a => 1 -- 3, 2, 1 -- GOOD
```

But it is false in 2 cases:

```
b => 2, c => 3, a => 1 -- 2, 3, 1 -- ERROR, should be 3, 1, 2
c => 3, a => 1, b => 2 -- 3, 1, 2 -- ERROR, should be 2, 3, 1
```

I'm not sure why I thought just `.values` would be okay, but I did. The correct way to generate the iterator is:

`.values.antipairs.sort».value` 

(I omitted the *-1 needed to get to actual 0-based indexes throughout this comment for brevity).

**Comment by zostay** [comment]
The `t/multi-hash.t` is still failing during delete because one of the POST conditions is failing. Still investigating that.

**Comment by AlexDaniel** [comment]
Any news?

**Comment by zostay** [comment]
Only that it fails some of the time, but not all of the time on my laptop and haven't tracked it down yet.

**Comment by zostay** [comment]
Releasing a fix for the multi-hash initializer test failure shortly. Unfortunately, there's another "Cannot assign to an immutable value" failure I'm about to report.
